package seedu.duke.commands;

public class InfoSuCommand extends InfoCommand {

    public InfoSuCommand() {
        super();
        super.description = "Welcome to Kolinux S/U Help Desk!\n"
                + "What is it about?\n"
                + "Under the S/U (Satisfactory/Unsatisfactory) option, students may choose to retain their letter \n"
                + "grade and include it in the computation of their CAP, or choose to exercise the S/U option.\n"
                + "In the case where the S/U option is exercised, the letter grade will not be shown on the \n"
                + "transcript and not included in the calculation of their CAP.\n\n"
                + "________________________________\n"
                + "|  Before S/U   |   After S/U  |\n"
                + "--------------------------------\n"
                + "|      A+       |              |\n"
                + "-----------------              |\n"
                + "|      A        |              |\n"
                + "-----------------              |\n"
                + "|      A-       |              |\n"
                + "-----------------              |\n"
                + "|      B+       |       S      |\n"
                + "-----------------              |\n"
                + "|      B        |              |\n"
                + "-----------------              |\n"
                + "|      B-       |              |\n"
                + "-----------------              |\n"
                + "|      C+       |              |\n"
                + "-----------------              |\n"
                + "|      C        |              |\n"
                + "-------------------------------|\n"
                + "|      D+       |              |\n"
                + "-----------------              |\n"
                + "|      D        |       U      |\n"
                + "-----------------              |\n"
                + "|      F        |              |\n"
                + "--------------------------------\n\n"
                + "Modular credits will only be counted towards graduation if the 'S' grade is achieved.\n\n"
                + "When does this exercise take place?\n"
                + "The S/U (Satisfactory/Unsatisfactory) option is exercised at the end of each \n"
                + "semester after exam results release.\n\n"
                + "What are the modules I can exercise this option on?\n"
                + "The general requirement is as follows:\n"
                + "- Level-1000 modules\n"
                + "- Level-2000 modules that do not have any prerequisites.\n"
                + "- All CELC level-2000 communication modules\n"
                + "For more specific details, please enter \"view [module code]\" to find out if the S/U option\n"
                + "can be exercised on the module.\n\n"
                + "Some tips when considering S/U\n"
                + "Do consider carefully if you wish to S/U a module, as it could result in unstable CAP.\n"
                + "Example:\n"
                + "You have just completed 5 modules and your CAP is the evenly weighted average of those 5.\n"
                + "If you choose to S/U 2 of the 5 modules, your CAP will be the average of only 3 modules.\n"
                + "The next module that will be counted towards your CAP will move your CAP more than if it was\n"
                + "an average of 5 modules.\n"
                + "Of course, the number of S/U students can exercise on modules is not infinite:\n"
                + "________________________________________________________________________\n"
                + "|         Non-Poly students         |           Poly students          |\n"
                + "------------------------------------------------------------------------\n"
                + "|  Up to 32MCs for first and second | Up to 20MCs for first and second |\n"
                + "|  semesters, with up to 12MCs for  |  semesters, with up to 12MCs for |\n"
                + "|  subsequent semesters if not      |  subsequent semesters if not     |\n"
                + "|       fully utilised.             |         fully utilised.          |\n"
                + "------------------------------------------------------------------------";
    }
}
